### ISSUE TITLE
Calling corpscon_v6-64bit.dll from Excel (office 365) VBA Windows 11

### ISSUE THREAD

**Issue by JohnRBattle** [dhawk/corpscon_v6_64bit.dll#1]
First of all, EXCELLENT WORK in preserving a truly useful program! When calling the .dll from VBA under the original file name corpscon_v6-64bit.dll an Error 48 file not found is returned...this is the same behavior as when using the 32 bit version of the file. (note : the 32 bit version worked fine with VBA under windows 10...the problem arose upon an update to Windows 11).  The file seems to work fine after changing the file name from corpscon_v6-64bit.dll corpscon_v6.dll with the exception of a popup window reporting the change in the file name.  Can the popup message be suppressed?

Thanks for preserving such an important program!!!!!!!!

**Comment by dhawk** [comment]
John,

It sounds like you are in “DLL hell”.  Microsoft has done various things over the years to make all this work better, and I tried to find a middle ground between the assumptions made when the Army Corps wrote the original, and what might work today under various bitness environments.

I’m at a bit of a disadvantage in responding because I don’t have access to either Windows 11 or to VBA 64-bit.  I see from the Microsoft website that you cannot have both 32-bit and 64-bit VBA on the same machine, so when you updated your VBA to 64-bit, did you also update all your declarations to change “libname” from “corpscon_v6.dll” to “corpscon_v6_64bit.dll” in the declarations for the functions?   

[Public | Private] Declare Sub name Lib "corpscon_v6_64bit.dll" [Alias "aliasname"] [([arglist])]
[Public | Private] Declare Function name Lib "corpscon_v6_64bit.dll" [Alias "aliasname"] [([arglist])] [As type]

If you want to keep your source code both 32 and 64 bit compatible, then you can enclose the declarations in conditionals:

#if Win64 then
   Declare … Lib "corpscon_v6_64bit.dll" …
#else
   Declare … Lib "corpscon_v6.dll" …
#end if

Does this do the trick?

Dave

**Comment by JohnRBattle** [comment]
Dave,

Thank you so much for taking the time to respond...

 I will give your suggestions a try this evening and let you know how it
works out!

Sincerely,

John Battle

**Comment by JohnRBattle** [comment]
Dave,

Updating the declarations for the functions as you suggested fixed the problem and everything seems to work perfectly now!

Once again, great work here!

John
